Página de Checkout
IntegraRU/integraru-frontend pull request #37
Opened 2022-11-28 00:16 UTC by LucianErick

[IntegraRU.webm](https://user-images.githubusercontent.com/50140883/204167628-6f757b7a-72e8-42a3-8973-99ae37eb4efe.webm)

2022-11-28 22:04 UTC, franklingg requested changes
Em telas pequenas, o texto fica muito quebrado. Você poderia definir um limite máximo pro tamanho da imagem `max-width: 40%`, por exemplo (você vê o valor que fica mais razoável), pra evitar isso. No geral ficou muito bom!
![image](https://user-images.githubusercontent.com/61962950/204390499-d6bdb7c1-4cb4-4bc1-aecd-a920849ddeb9.png)

2022-11-28 22:04 UTC, franklingg commented on src/pages/Checkout/Checkout.js
> +  }
Ao testar, vi que o botão dispara o alert duas vezes. Usando um useCallback vc evita que esse componente seja re-renderizado e evita problemas.
```suggestion
  const handleConfirm = useCallback(() => {
    alert('Confirmando');
    // TODO: BACK
    navigate(-1)
  }, []);
```

2022-11-28 22:04 UTC, franklingg commented on src/pages/Checkout/Checkout.js
> +            {formatDate(menuData.date)}
Essa função não é necessária, a biblioteca `date-fns` já tem métodos pra isso
```suggestion
        import {format} from 'date-fns';
        [...]
        {format(menuData.date, 'dd/MM/yyyy')}
```

2022-11-28 23:13 UTC, franklingg requested changes

2022-11-28 23:13 UTC, franklingg commented on src/pages/Checkout/Checkout.js
> +        [...]
Eu coloquei na sugestão mas não seria exatamente como colocar no código, dessa forma aqui quebra (o import é no inicio do arquivo) e esse [...] não é código

2022-11-28 23:13 UTC, franklingg commented on src/pages/Checkout/Checkout.js
> +};
como a função é desnecessária, é necessário removê-la.

2022-11-28 23:13 UTC, franklingg commented on src/pages/Checkout/Checkout.js
> +  const handleConfirm = useCallback(() => {
É preciso importar também para usá-lo

2022-11-29 13:17 UTC, LucianErick commented
ata, eu pensei que tu tinha inserido as mudanças diretamente kkkk mals

2022-12-02 17:13 UTC, franklingg approved these changes
Tudo certo!

2022-12-02 17:13 UTC, merged